### ISSUE TITLE
strip_path on the route object does nothing

### ISSUE THREAD

**Issue by nvx** [Kong/kong-plugin-grpc-web#7]
```
_format_version: "1.1"

services:
  - protocol: grpc
    host: 127.0.0.1
    port: 1234
    routes:
      - protocols:
          - http
        paths:
          - /foobar
        strip_path: true
        plugins:
          - name: grpc-web
```

With the above configuration, I would expect to be able to hit eg `http://127.0.0.1:8000/foobar/package.Service/Method` and have it be equivalent of hitting `http://127.0.0.1:8000/package.Service/Method` if the route path was / as far as the backend gRPC service is concerned.

In practice, a gRPC error is instead returned `unknown service foobar/package.Service`

It looks like the path is coming from `kong_request_get_path()` in https://github.com/Kong/kong-plugin-grpc-web/blob/536dd5b/kong/plugins/grpc-web/handler.lua#L46

I'm not sure if it's possible to re-use the existing router logic (I see `kong.service.request.set_path`, but no `kong.service.request.get_path` which would have been my first guess) or if the trimming needs to be implemented separately in the grpc-web plugin.
